Web/Controllers/ProjectosController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using Domain.Abstract;
using Domain.Concrete;
using Domain.Entities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Web.Models;

namespace Web.Controllers
{
    public class ProjectosController : Controller
    {
        private readonly MovimentaContext db = new MovimentaContext();
        private readonly IProjectoRepository projectoRepository;

        public ProjectosController(IProjectoRepository repository)
        {
            projectoRepository = repository;
            //trabalhosRepository = trabalhos;

            try
            {
                ViewBag.Membro = GetUserLogedIn().Membro;
            }
            catch (NullReferenceException e)
            {
                System.Console.WriteLine(e.Message);
            }
        }

        private ApplicationUser GetUserLogedIn()
        {
            var user =
                System.Web.HttpContext.Current.GetOwinContext()
                    .GetUserManager<ApplicationUserManager>()
                    .FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());

            return user;
        }

        // GET: Projectos
        public ActionResult Index(int? page)
        {
            var intpage = 1;
            if (page != null) intpage = page.Value;

            Debug.WriteLine("page: " + intpage);
            var projectos = projectoRepository.GetProjectosWithPage(intpage, 6,projectoRepository.ListaProjectosUsuario()).ToList();
            var model = new CampanhaViewModel
            {
                Projectos = projectos,
                paginator = new CampanhaViewModel.Paginator(intpage, projectoRepository.ListaProjectosUsuario())
            };
            return View(model);
        }

        // GET: Projectos/Detalhe/5
        public ActionResult Detalhe(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var projecto = db.Projectos.Find(id);
            if (projecto == null)
            {
                return HttpNotFound();
            }

            var model = new DetalheViewModel
            {
                ProjectoId = projecto.ProjectoId,
                Titulo = projecto.Titulo,
                Keywords = projecto.Keywords,
                FotoUrl = projecto.Foto,
                Video = projecto.Video,
                DescricaoCurta = projecto.Descricao,
                SobreCampanha = projecto.Sobre,
                UsoFundo = projecto.Objectivofundo,
                Progresso = projecto.GetProgresso(),
                Arrecadado = projecto.Arrecadado ?? 0,
                Meta = projecto.Meta ?? 0,
                DataFim = projecto.DataFim ?? DateTime.Today,
                DataInicio = projecto.DataInicio ?? DateTime.Today,
                Novidades = db.Novidades.Where(nov => nov.ProjectoId == projecto.ProjectoId),
                Comentarios = db.Comentarios.Where(com => com.ProjectoId == projecto.ProjectoId).OrderByDescending(com => com.Data).Take(7),
                Movimentadores = db.Movimentadores.Where(mov => mov.ProjectoId == projecto.ProjectoId),
                Recompensas = db.Recompensas.Where(rec => rec.ProjectoId == projecto.ProjectoId),
                Autor = db.Membros.Find(projecto.MembroId),
                Projectos = projectoRepository.GetRelatedProjects(projecto).Take(3).ToList()
            };
            
            return View(model);
        }

        [Authorize(Roles = "adm")]
        public ActionResult Previsualizar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var projecto = db.Projectos.Find(id);
            if (projecto == null)
            {
                return HttpNotFound();
            }

            var model = new DetalheViewModel
            {
                ProjectoId = projecto.ProjectoId,
                Titulo = projecto.Titulo,
                Keywords = projecto.Keywords,
                FotoUrl = projecto.Foto,
                Video = projecto.Video,
                DescricaoCurta = projecto.Descricao,
                SobreCampanha = projecto.Sobre,
                UsoFundo = projecto.Objectivofundo,
                Progresso = projecto.GetProgresso(),
                Arrecadado = projecto.Arrecadado ?? 0,
                Meta = projecto.Meta ?? 0,
                DataFim = projecto.DataFim ?? DateTime.Today,
                DataInicio = projecto.DataInicio ?? DateTime.Today,
                Novidades = db.Novidades.Where(nov => nov.ProjectoId == projecto.ProjectoId),
                Comentarios = db.Comentarios.Where(com => com.ProjectoId == projecto.ProjectoId).OrderByDescending(com => com.Data).Take(7),
                Movimentadores = db.Movimentadores.Where(mov => mov.ProjectoId == projecto.ProjectoId),
                Recompensas = db.Recompensas.Where(rec => rec.ProjectoId == projecto.ProjectoId),
                Autor = db.Membros.Find(projecto.MembroId),
                Projectos = new MovimentaContext().Projectos.Take(3).ToList()
            };
            model.Projectos = new MovimentaContext().Projectos.Take(3).ToList();
            
            return View("Detalhe", model);
        }

        // GET: Projectos/Criar
        [Authorize]
        public ActionResult Criar()
        {
            var model = new CriarViewModel();
            var campanhas =
                new MovimentaContext().Campanhas.Select(
                    campanha => new SelectListItem {Text = campanha.Nome, Value = campanha.CapanhaId.ToString()})
                    .ToList();
            model.Campanha = new SelectList(campanhas, "Value", "Text", model.CampanhaSelecionada);
            return View(model);
        }

        // POST: Projectos/Criar
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Criar")]
        [ValidateAntiForgeryToken]
        [Authorize]
        //public ActionResult Criar([Bind(Include = "ProjectoId,MembroId,Titulo,Foto,Descricao,Sobre,Objectivofundo,Campanha,Meta,Arrecadado,DataInicio,DataFim")] Projecto projecto)
        public ActionResult Criar(CriarViewModel model)
        {
            if (ModelState.IsValid)
            {
                
                db.Enderecos.Add(new Endereco {IdPais = 1,IdProvincia = 11,IdMunicipio = 95,Rua = "Coloque a rua"});
                db.SaveChanges();
                var endereco = new EnderecoCampanha {EnderecoId = db.Enderecos.ToList().Last().EnderecoId};
                db.EnderecoCampanhas.Add(endereco);
                db.SaveChanges();

                var projecto = new Projecto
                {
                    Titulo = model.Titulo,
                    MembroId = getUserLogedIn().MembroId,
                    Estado = Estado.Rascunho,
                    IdLocalizacao = endereco.IdLocalizacao
                };
                projectoRepository.AddProjecto(projecto);
                db.SaveChanges();

                //db.Projectos.Add(projecto);
                //db.SaveChanges();
                return RedirectToAction("Editar",
                    new {Id = projectoRepository.GetProjectos(getUserLogedIn().MembroId).ProjectoId});
            }
            return View(model);
        }

        private ApplicationUser getUserLogedIn()
        {
            var user =
                System.Web.HttpContext.Current.GetOwinContext()
                    .GetUserManager<ApplicationUserManager>()
                    .FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());

            return user;
        }

        // GET: Projectos/Editar
        [Authorize]
        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var idprojecto = (int) id;
            var projecto = projectoRepository.GetProjectos(idprojecto);
            if (projecto == null)
            {
                return HttpNotFound();
            }
            if (!projecto.MembroId.Equals(GetUserLogedIn().MembroId))
            {
                return HttpNotFound();
            }

            var enderecocampanha = projecto.GetEnderecoCampanha();

            var model = new EditarViewModel
            {
                ProjectoId = projecto.ProjectoId,
                Titulo = projecto.Titulo,
                Foto = projecto.Foto,
                Video = projecto.Video,
                Descricao = projecto.Descricao,
                Sobre = projecto.Sobre,
                Objectivofundo = projecto.Objectivofundo,
                //Local = projecto.EnderecoCampanha,
                Keywords = projecto.Keywords,
                DiasArrecadacao = projecto.Duracao??0,
                Meta = projecto.Meta,
                CampanhaSelecionada = projecto.CapanhaId.ToString(),
                CategoriaSelecionada = projecto.CategoriaId.ToString(),
                Estado = projecto.Estado,
                PaisSelecionado = enderecocampanha.IdPais.ToString(),
                ProvinciaSelecionada = enderecocampanha.IdProvincia.ToString(),
                MunicipioSelecionado = enderecocampanha.IdMunicipio.ToString(),
                Rua = enderecocampanha.Rua
            };

            var categorias =
                db.Categorias.Select(
                    categoria => new SelectListItem {Text = categoria.nome, Value = categoria.CategoriaId.ToString()})
                    .ToList();

Web/Controllers/SupportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Web.Models;

namespace Web.Controllers
{
    public class SupportController : Controller
    {

        public SupportController()
        {
            try
            {
                ViewBag.Membro = GetUserLogedIn().Membro;
            }
            catch (NullReferenceException e)
            {
            }
        }

        private ApplicationUser GetUserLogedIn()
        {
            var user =
                System.Web.HttpContext.Current.GetOwinContext()
                    .GetUserManager<ApplicationUserManager>()
                    .FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());

            return user;
        }

        // GET: Support
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Privacy()
        {
            return View();
        }

        public ActionResult Faq()
        {
            return View();
        }

        public ActionResult Rules()
        {
            return View();
        }

        public ActionResult Terms()
        {
            return View();
        }
    }
}

Web/Views/Shared/_Carrossel.cshtml
@{
    var i = 0;
}
<div class="carousel slide" id="carrosel" data-ride="carousel" style="height: 294.333px;">
    <!--Indicadores-->
    <ol class="carousel-indicators"></ol>
    <!--Conteudo-->
    <div class="carousel-inner">
        @foreach (var slide in ViewBag.slides)
        {
            var classe = (i == 0) ? "carousel-item active" : "carousel-item";
            
            <div class='@classe'>
                <div class='@("img " + slide.BgColor)'>
                    @if (slide.BackImage != null)
                    {
                    var classeimage = slide.BackImage.ToString() == "" ? "dp-none" : "d-block w-100";
                    <img class='@classeimage' src='@("/Content/img/" + slide.BackImage)' />
                    }
                   
                    <div class="carousel-caption d-none d-md-block">
                        <h2 class='@slide.FgColor'>@slide.Titulo</h2><br/>
                        <h5 class='@slide.FgColor'>@slide.Descricao</h5><br/>
                        @*<p><button type="button" class="btn btn-lg btn-block btn-outline-primary">Saiba como &raquo;</button></p>*@
                        <a href='@slide.GoLink' id="carrosel-GoBtn" class="btn btn-lg btn-block btn-outline-primary" style="width: 200px;">Saiba como &raquo;</a>
                        <br/>
                    </div>
                </div>
            </div>
            i++;
        }
     </div>
    <!--Controles-->
    <a class="carousel-control-prev" href="#carrosel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Anterior</span>
    </a>
    <a class="carousel-control-next" href="#carrosel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Seguinte</span>
    </a>


    <script>
        /*************************************************************************************************/

        //const carrossel = document.getElementById("carrosel");
        //const carrosel_slides = carrossel.querySelectorAll(".carousel-item");
        //const carrossel_indicators = carrossel.querySelector(".carousel-indicators");

        //var numi = 0, classe = "";
        //carrosel_slides.forEach(() => {
        //    classe = (numi === 0) ? "active" : "";
        //    carrossel_indicators.innerHTML += '<li data-target="#carrosel" data-slide-to="' + numi + '" class="' + classe + '"></li>';
        //    numi++;
        //});
    </script>
</div>

Web/Views/Shared/_Footer.cshtml
<footer class="xs-footer-section fundpress-footer-section v3">
    <div class="fundpress-footer-top-layer">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <div class="fundpress-single-footer">
                        <div class="xs-footer-logo">
                            <a href="/">
                                <img src="/Content/images/logo2.png" alt="" style="width: 300px;">
                            </a>
                        </div>
                        <div class="fundpress-footer-content">
                            <p>A movimenta levanta capital para projectos pelos quais tens paixão. Somos uma solução inovadora e construída a medida do mercado angolano para ajudar projectos e ideas reais</p>
                        </div><!-- . END -->
                        <ul class="xs-social-list fundpress-social-list">
                            <li><a href="" class="color-facebook full-round"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="" class="color-twitter full-round"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="" class="color-instagram full-round"><i class="fa fa-instagram"></i></a></li>
                        </ul><!-- .xs-social-list .fundpress-social-list END -->
                    </div><!-- .fundpress-single-footer END -->
                </div>
                <div class="col-md-3">
                    <div class="fundpress-single-footer">
                        <div class="xs-footer-title">
                            <h4 class="color-white">Explora campanhas</h4>
                        </div><!-- .xs-footer-title END -->
                        <nav class="xs-footer-menu">
                            <ul>
                                <li><a href="/">Início</a></li>
                                <li><a href="#">Ciência e Tecnologia</a></li>
                                <li><a href="#">Sociedade</a></li>
                                <li><a href="#">Cultura e Artes</a></li>
                                <li><a href="#">Jogos</a></li>
                                <li><a href="#">Literatura</a></li>
                            </ul>
                        </nav><!-- .xs-footer-menu .xs-block-menu END -->
                    </div><!-- .fundpress-single-footer END -->
                </div>
                <div class="col-md-2">
                    <div class="fundpress-single-footer">
                        <div class="xs-footer-title">
                            <h4 class="color-white">Sobre</h4>
                        </div><!-- .xs-footer-title END -->
                        <nav class="xs-footer-menu">
                            <ul>
                                <li>@Html.ActionLink("Sobre Nós","About","Home")</li>
                                <li>@Html.ActionLink("Como funciona","About","Home")</li>
                                
                                <li><a href="/Home/#partners">Parceiros</a></li>
                                <li><a href="http://blog.movimenta.ao">Blog</a></li>
                                <li>@Html.ActionLink("Contácte-nos", "Contact", "Home")</li>
                            </ul>
                        </nav><!-- .xs-footer-menu .xs-block-menu END -->
                    </div><!-- .fundpress-single-footer END -->
                </div>
                <div class="col-md-2">
                    <div class="fundpress-single-footer">
                        <div class="xs-footer-title">
                            <h4 class="color-white">Ajuda</h4>
                        </div><!-- .xs-footer-title END -->
                        <nav class="xs-footer-menu">
                            <ul>
                                <li>@Html.ActionLink("Perguntas Frequentes", "Faq", "Support")</li>
                                <li>@Html.ActionLink("Nossas Regras", "Rules", "Support")</li>
                                <li><a href="/Home/#security">Confiança e segurança</a></li>
                                <li>@Html.ActionLink("Suporte", "Index", "Support")</li>
                                <li>@Html.ActionLink("Termos de uso", "Terms", "Support")</li>
                                <li>@Html.ActionLink("Política de privacidade", "Privacy", "Support")</li>
                            </ul>
                        </nav><!-- .xs-footer-menu .xs-block-menu END -->
                    </div><!-- .fundpress-single-footer END -->
                </div>
            </div>
        </div>
    </div><!-- .xs-footer-wraper .fundpress-footer-top-layer END -->
    <div class="xs-footer-bottom-layer fundpress-footer-bottom">
        <div class="container">
            <div class="xs-footer-bottom-wraper">
                <div class="xs-copyright-text fundpress-copyright-text">
                    <p>&copy; 2020 - @DateTime.Now.Year TELLINE - Tecnologia e Inovação. Todos os direitos reservados</p>
                </div>
                <div class="xs-back-to-top-wraper">
                    <a href="#" class="xs-back-to-top full-round green-btn xs-back-to-top-btn show-last-pos">
                        <i class="fa fa-angle-up"></i>
                    </a>
                </div><!-- .xs-back-to-top-wraper END -->
            </div>
        </div>
    </div><!-- .xs-footer-bottom-layer .fundpress-footer-bottom END -->
</footer>

Web/Views/Shared/_HeadMenu.cshtml
<!-- header version inner menu -->
<header class="xs-header-height xs-menu-style-solid xs-menu-style-border fundpress-header-main-version color-navy-blue  v3">
    <div class="container">
        <nav class="xs-menus fundpress-menu">
            <div class="nav-header">
                <div class="nav-toggle"></div>
                <a class="nav-brand nav-logo" href="index.html">
                    <img src="/Content/images/logo1.png" alt="">
                </a>
            </div><!-- . END -->
            <div class="nav-menus-wrapper">
                <div class="xs-logo-wraper">
                    <a class="nav-brand xs-logo fundpress-logo-v1" href="/">
                        <img src="/Content/images/logo0.png" alt="">
                    </a>
                </div>
                <ul class="nav-menu">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>
                        <a href="#">Como funciona</a>
                        <ul class="nav-dropdown">
                            <li><a href="http://blog.movimenta.ao">Blog</a></li>
                            <li><a href="#">Como iniciar uma campanha</a></li>
                            <li><a href="#">Requisitos</a></li>
                            <li><a href="#">Como financiar</a></li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Contacte-nos","Contact","Home")</li>
                </ul>
                <div class="xs-navs-button">
                    <ul class="xs-icon-with-text fundpress-icon-menu">
                        <li class="d-block d-lg-none d-xl-block">@Html.ActionLink("Iniciar uma campanha", "Criar", "Projectos", null, new {@class = "xs-btn round-btn green-btn"})</li>
                        <li>@Html.Partial("_LoginPartial")</li>
                    </ul>
                </div>
            </div><!-- .nav-menus-wrapper END -->
        </nav><!-- .xs-menus .fundpress-menu END -->
    </div>
</header>
<!-- header version inner menu closed -->

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <title>Movimenta - @ViewBag.Title</title>

    <meta name="description" content="Plataforma de financiamento colaborativo (crowdfunding). Uma opção de financiamento para pôr as ideias em práticas. Mais do que juntar dinheiro, na Movimenta, criamos uma comunidade em torno do seu projecto/ideia."/>
    <meta name="keyword" content="movimenta crowdfunding financiamento colaborativo apoio"/>

    <link rel="icon" type="image/png" href="/favicon.ico">

    <link href="/Content/css/iconfont.css" rel="stylesheet" />
    <link href="/Content/css/font-awesome.min.css" rel="stylesheet" />
    <link href="/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/Content/css/isotope.css" rel="stylesheet" />
    <link href="/Content/css/magnific-popup.css" rel="stylesheet" />
    <link href="/Content/css/owl.carousel.min.css" rel="stylesheet" />
    <link href="/Content/css/owl.theme.default.min.css" rel="stylesheet" />
    <link href="/Content/css/woocommerce.css" rel="stylesheet" />
    <link href="/Content/css/plugins.css" rel="stylesheet" />
    <link href="/Content/css/style.css" rel="stylesheet" />
    <link href="/Content/css/responsive.css" rel="stylesheet" />
    <link href="/Content/css/site.css" rel="stylesheet" />

    <script>
        function docReady(fn) {
            if (document.readyState === 'complete' || document.readyState === 'interactive') {
                setTimeout(fn, 1);
            } else {
                document.addEventListener('DOMContentLoaded', fn);
            }
        }
    </script>
    <!--Facebook;Pixel;Code -->
    <script>
        !function(f, b, e, v, n, t, s) {
            if (f.fbq)return;
            n = f.fbq = function() {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments);
            };
            if (!f._fbq)f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s);
        }(window, document, 'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '620305282698331');
        fbq('track', 'PageView');
    </script>
    <noscript>
        <img height="1" width="1" src="https://www.facebook.com/tr?id=620305282698331&ev=PageView&noscript=1"/>
    </noscript>
    <!-- End Facebook Pixel Code -->
    <!-- Hotjar Tracking Code for www.movimenta.ao -->
    <script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:2407503,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>

</head>
<body class="woocommerce">
<!--[if lt IE 10]>
    <p class="browserupgrade">Voçê está usando um navegador <strong>desactualizado</strong>. <a href="http://browsehappy.com/">Actualize seu navegador</a> para melhorar a sua experiência.</p>
<![endif]-->
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v10.0" nonce="d87lNpET"></script>
<div id="preloader">
    <div class="spinner">
        <div class="double-bounce1"></div>
        <div class="double-bounce2"></div>
    </div>
</div><!-- #preloader -->

@Html.Partial("_HeadMenu")

@Html.Partial("_ModalLoginRegister")

@RenderBody()


@Html.Partial("_Footer")


    <script src="/Content/js/jquery-3.2.1.min.js"></script>

    <script src="/Content/js/Popper.js"></script>
    <script src="/Content/js/bootstrap.min.js"></script>
    <script src="/Scripts/respond.js"></script>

    <script src="/Content/js/plugins.js"></script>
    <script src="/Content/js/isotope.pkgd.min.js"></script>
    <script src="/Content/js/jquery.easing.1.3.js"></script>
    <script src="/Content/js/jquery.countdown.min.js"></script>
    <script src="/Content/js/jquery.magnific-popup.min.js"></script>
    <script src="/Content/js/owl.carousel.min.js"></script>
    <script src="/Content/js/parallax.min.js"></script>
    <script src="/Content/js/jquery.easypiechart.min.js"></script>
    <script src="/Content/js/jquery.waypoints.min.js"></script>
    <script src="/Content/js/scrollax.js"></script>
    <script src="/Content/ckeditor/ckeditor.js"></script>
    <script src="/Content/js/main.js"></script>
    <script src="/Content/js/site.js"></script>


</body>
</html>

Web/Views/Shared/_LayoutBranco.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <title>Movimenta -  @ViewBag.Title</title>

    <link href="/Content/css/iconfont.css" rel="stylesheet" />
    <link href="/Content/css/font-awesome.min.css" rel="stylesheet" />
    <link href="/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/Content/css/isotope.css" rel="stylesheet" />
    <link href="/Content/css/magnific-popup.css" rel="stylesheet" />
    <link href="/Content/css/owl.carousel.min.css" rel="stylesheet" />
    <link href="/Content/css/owl.theme.default.min.css" rel="stylesheet" />
    <link href="/Content/css/woocommerce.css" rel="stylesheet" />
    <link href="/Content/css/plugins.css" rel="stylesheet" />
    <link href="/Content/css/style.css" rel="stylesheet" />
    <link href="/Content/css/responsive.css" rel="stylesheet" />
    <link href="/Content/css/site.css" rel="stylesheet" />

</head>
<body class="woocommerc" style="background-color: #808080;">
    <!--[if lt IE 10]>
                <p class="browserupgrade">Voçê está usando um navegador <strong>desactualizado</strong>. <a href="http://browsehappy.com/">Actualize seu navegador</a> para melhorar a sua experiência.</p>
            <![endif]-->

<div id="preloader">
    <div class="spinner">
        <div class="double-bounce1"></div>
        <div class="double-bounce2"></div>
    </div>
</div>

<main class="col-lg-4 bg-white" style="margin: 0 auto;">

    @RenderBody()
</main>
    <script src="/Content/js/jquery-3.2.1.min.js"></script>

    <script src="/Content/js/Popper.js"></script>
    <script src="/Content/js/bootstrap.min.js"></script>
    <script src="/Scripts/respond.js"></script>

    <script src="/Content/js/plugins.js"></script>
    <script src="/Content/js/isotope.pkgd.min.js"></script>
    <script src="/Content/js/jquery.easing.1.3.js"></script>
    <script src="/Content/js/jquery.countdown.min.js"></script>
    <script src="/Content/js/jquery.magnific-popup.min.js"></script>
    <script src="/Content/js/owl.carousel.min.js"></script>
    <script src="/Content/js/parallax.min.js"></script>
    <script src="/Content/js/jquery.easypiechart.min.js"></script>
    <script src="/Content/js/jquery.waypoints.min.js"></script>
    <script src="/Content/js/scrollax.js"></script>
    <script src="/Content/ckeditor/ckeditor.js"></script>
    <script src="/Content/js/main.js"></script>
    <script src="/Content/js/site.js"></script>
</body>
</html>